version: '3.8'

services:
  photovision:
    build: .
    container_name: photovision
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SMUGMUG_API_KEY=${SMUGMUG_API_KEY}
      - SMUGMUG_API_SECRET=${SMUGMUG_API_SECRET}
      - PORT=${PORT:-3001}
      - NODE_ENV=production
    volumes:
      # Persist data directory
      - ./data:/app/data
      # For development: uncomment to enable hot reload
      # - ./public:/app/public
      # - ./lib:/app/lib
      # - ./utilities:/app/utilities
      # - ./server.js:/app/server.js
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-3001}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: photovision-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - photovision
    restart: unless-stopped
    profiles:
      - production

# Development database viewer (optional)
  # json-server:
  #   image: vimagick/json-server
  #   container_name: photovision-db-viewer
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./data:/data
  #   command: --watch /data/images.json --port 3000 --host 0.0.0.0
  #   profiles:
  #     - development